#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# app_security:
#     path: /authenticate
#     controller: SSH\MyJwtBundle\Controller\SecurityController::authenticateAction